#!/usr/bin/env bash

set -e

exit_script() {
  echo 'Exiting...'
}

get_version() {
  go run main.go --version | cut -d " " -f 3
}

get_help_text() {
  go run main.go --help
}

update_readme() {
  # prepend notice
  readme=$'<!-- Autogenerated file. Do not edit. -->\n\n'

  # read template
  readme="$readme$(cat ./templates/README.md)"

  # update version
  readme="${readme//%version%/"$(get_version)"}"

  # update help
  readme="${readme//%help%/"\`\`\`"$'\n'"$(get_help_text)"$'\n'\`\`\`""}"

  # write file
  echo "$readme" >README.md
}

do_stuff() {
  update_readme
  echo 'Updated readme'

  git add README.md
  git commit --amend --no-edit

  echo 'Amended commit to add readme'

  git tag v"$(get_version)"

  echo 'Tagged release commit'
}

main() {
  read -r -p "Did you increment the version? (y/N)? " choice
  case "$choice" in
  y | Y) do_stuff ;;
  *) exit_script ;;
  esac
}

main
